version: 0.2

run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
  build:
    commands:
      - echo Install Deps
      - yarn
      - echo Build Production
      - cd ./client && yarn && yarn build && cd ..
      - yarn deploy
  post_build:
    commands:
      - echo Folder Change
      - find ./ -mindepth 1 ! -regex '^./prod-build\(/.*\)?' -delete
      - mv ./prod-build/* ./ 
artifacts:
  files:
    - '**/*'
  name: deploy-$(date +%Y-%m-%d).zip 
