version: 0.2

run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
  build:
    commands:
      - echo Install Deps
      - yarn
      - echo Build Production
      - yarn deploy
  post-build:
    commands:
      - echo Folder Change
      - find ./ -mindepth 1 ! -regex '^./prod-build\(/.*\)?' -delete
      - mv ./prod-build/* ./ 
