version: 0.2

run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
  build:
    commands:
      - echo Install Deps
      - yarn
      - echo Build Production
      - cd ./client && yarn && yarn build && cd ..
      - yarn deploy
artifacts:
  files:
    - prod-build/react-nodejs.zip
  name: deploy-$(date +%Y-%m-%d).zip 
