export const color = {
  lightenPrimary: '#d4bbbf',
  primary: '#dbc6c9',
  drakenPrimary: '#aa7980',
  secondary: '#e2cbb1',
  gray: '#ebedef',
  lightGray: '#f5f3f2',
  pink: '#fcf',
  white: '#fff',
  black: '#333',
  red: 'red',
  green: '#2eb85c',
  lightGreen: 'lightgreen',
  adminBackground: '#ECECEC',
  logoColor: '#f9eac3',
  yellowChart: '#f9b115',
  redChart: '#e55353',
  blueChart: '#39f',
  greenChart: '#2eb85c'
}
