export const color = {
  lightenPrimary: '#d4bbbf',
  primary: '#dbc6c9',
  drakenPrimary: '#aa7980',
  secondary: '#F9EAC3',
  gray: '#ebedef',
  lightGray: '#f5f3f2',
  pink: '#fcf',
  white: '#F9F9F9',
  black: '#2F1B0F',
  red: '#F21B3F',
  green: '#2eb85c',
  blue: '#08BDBD',
  yellow: '#FF9914',
  lightGreen: 'lightgreen',
  adminBackground: '#ECECEC',
  logoColor: '#f9eac3',
  yellowChart: '#f9b115',
  redChart: '#e55353',
  blueChart: '#39f',
  greenChart: '#2eb85c'
}
